RohanKumar01/Leet-Code

Solutions/longest_palindromic_subsequence.cpp
Dynamic Programming based C++ program for LPS problem
=> Created longest_palindromic_subsequence.cpp

Question/solutions
Here I Solve a Leetcode Problem Longest Increasing Subsequence II using  C++ Segment Tree
=> Leetcode Problem With Solution

Solutions/kmp_algorithm.cpp
C++ program for implementation of KMP pattern searching algorithm
=> Created kmp_algorithm.cpp

Question Links, Solutions/Nqueens.cpp
added one of my , solved probelm  , Named : nqueens with recursion
=> added nQueen problem with Soln || Very Im || with comments

Solutions/Minimum Window Substring
=> Minimum Window Substring

Solutions/Longest Ideal Subsequence
=> Longest Ideal Subsequence

Solutions/Substring with Concatenation of All Words
=> Substring with Concatenation of All Words

Solutions/Reverse Integer
Reverse Integer LeetCode  Medium Level Question
=> Create Reverse Integer

Solutions/Merge Two Sorted List
Merge Two Sorted List Leet Code Question
=> Create Merge Two Sorted List

Solutions/Add Two Number IN LinkedList
this is a Leet Code Question Full Submition
=> Create  Add Two Number IN LinkedList

Solutions/longestValidParentheses.py
Given a string containing just the characters '(' and ')', find the length of the longest valid (well-formed) parentheses substring.
=> longestValidParentheses.py

Solutions/Reverse Words in a String III
=> Create Reverse Words in a String III

Solutions/Build Array from Permutation
=> Create Build Array from Permutation

Squares of a Sorted Array
=> Create Squares of a Sorted Array

shuffle the Array
=> Create shuffle the Array

special-array-with-x-elements-greater-than-or-equal-x
special-array-with-x-elements-greater-than-or-equal-x  solved leetcode ques
=> special array

Solutions/flatten_binary_tree_to_linked_list.cpp
C++ program to flatten a binary tree to linked list
=> Created flatten_binary_tree_to_linked_list.cpp

Solutions/lca_bst.cpp
Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST.
=> Created lca_bst.cpp

Solutions/add_two_strings.cpp
Given two non-negative integers, num1 and num2 represented as string, return the sum of num1 and num2 as a string.
=> Created add_two_strings.cpp

Solutions/max_width_binary_tree.cpp
Given the root of a binary tree, return the maximum width of the given tree.
=> Created max_width_binary_tree.cpp

Solutions/largest_value_rowwise_binary_tree.cpp
Given the root of a binary tree, return an array of the largest value in each row of the tree
=> Created largest_value_rowwise_binary_tree.cpp

Important Questions, Solutions/balance-a-binary-search-tree.cpp
C++ program added to balance BST
=> Leetcode solution to balance a Binary Search Tree

Solutions/572_is_subtree.cpp
Given the roots of two binary trees root and subRoot, return true if there is a subtree of root with the same structure and node values of subRoot and false otherwise.
=> Created 572_is_subtree.cpp

Solutions/735_asteroid_collision.cpp
Asteroid Collision Problem in Linear time and space complexity
=> Created 735_asteroid_collision.cpp

Solutions/Redundant Brackets
Important problem of Stack Data Structure 'Redundant Brackets'
=> Redundant Brackets

Solutions/Remove Nth node from end of List
Hey please merge this to your repository.
=> Create Remove Nth node from end of List

Solutions/Largest Rectangle in Histogram
Leet Code Hard level Questions of Stack Data Structure
=> Largest Rectangle in Histogram

Solutions/1255. Maximum Score Words Formed by Letters
Very important || day17 Problem of 30Days of code of Scaler || LeetCode || Interview
=> 1255. Maximum Score Words Formed by Letters

Solutions/Longest Valid Parentheses
=> Longest Valid Parentheses

Solutions/Implement Stack Using Queue
Important || LeetCode || 200Views || Intersting || 100%Faster
=> Created Implemented Stack From Queue

Solutions/Regular Expression Matching
Dp || Leetcode || Very Important || DSA || FANG
=> Regular Expression Matching

Solutions/4. Median of Two Sorted Arrays
Brute To Optimized || LeetCode || Very Important || Hard || @FANG || MustDo
=> Median Of 2 Sorted Array

Solutions/The Skyline Problem
=> The Skyline Problem

KthElement
=> KthElement

Solutions/132 Pattern
LeetCode || Medium || Intersting || Very Important
=> Create 132 Pattern

Solutions/Encode and Decode TinyURL
LeetCode || Medium || Must Do || Cp
=> Create Encode and Decode TinyURL

Solutions/765. Couples Holding Hands
LeetCode || HARD || V Imp  || FANG
=> Create  Couples Holding Hands

Solutions/458. Poor Pigs
LeetCode || Hard || Very Important || 100.00% of Optimise space complexity || FANG
=> Create  Poor Pigs File

Solutions/206. reverse_list.cpp
Given the head of a singly linked list, reverse the list, and return the reversed list.
=> Created reverse_list.cpp

Solutions/Zigzag-Conversion.cpp
Please Merge this PR in the main this question is very famous and challenging problem on Leetcode.
=> Zigzag-Conversion

Solutions/540. Single_Element_in_a_Sorted_Array.cpp
You are given a sorted array consisting of only integers where every element appears exactly twice, except for one element which appears exactly once. Return the single element that appears only once.
=> 540. Single_Element_in_a_Sorted_Array.cpp

213.HouseRobberII.cpp
Added solution for problem 213. House Robber II with O(N) time complexity and  O(1) space complexity.
=> Added solution for problem 213. House Robber II

Solutions/445. Add-Two-Numbers-II.cpp
You are given two non-empty linked lists representing two non-negative integers. The most significant digit comes first and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.
=> 445. Add-Two-Numbers-II.cpp

32.LongestValidParentheses.cpp, 48.RotateImage.cpp
solution for leetcode problem 32. Longest Valid Parentheses using two pointer approach.
=> Added solution for leetcode problem 32. Longest Valid Parentheses

Solutions/Merge overlapping intervals.cpp
=> Merge overlapping intervals

Solutions/Text Justification
Cpp || LeetCode || Hard || Must Do || MAANG
=> Create  Text Justification

Solutions/Dota2 Senate
Cpp || Leetcode || Medium || String || Must Do
=> Create Dota2 Senate

Solutions/Super Washing Machines
Cpp || Leetcode ||  Greedy || Hard || Important
=> Create Washing Machines Problem

Solutions/Scramble String
Cpp || Leetcode || String || Dp || Recursion || Must Do
=> Create Scramble String

Solutions/maximum-product-of-two-elements-in-an-array.cpp
Please accept my pull request I added a new question of leetcode
=> maximum-product-of-two-elements-in-an-array

Solutions/630_CourseScheduleIII.cpp
@RohanKumar01 Please accept my pull request for the above leetcode problem.
Thanks!
=> Added solution to Course Schedule III problem

Solutions/76_Minimum_Window_Substring.cpp
Given two strings s and t of lengths m and n respectively, return the minimum window substring of s such that every character in t (including duplicates) is included in the window. If there is no such substring, return the empty string "".
=> Created 76_Minimum_Window_Substring.cpp

Solutions/74_search_2d_matrix.cpp
Write an efficient algorithm that searches for a value target in an m x n integer matrix matrix. This matrix has the following properties:
Integers in each row are sorted from left to right. The first integer of each row is greater than the last integer of the previous row.
=> Created 74_search_2d_matrix.cpp

Solutions/174. Dungeon Game
Added Dp Solution of Dungeon Game Problem of leetcode.
Please merger my request.
=> Create 174. Dungeon Game

Solutions/146_LRU_Cache.cpp
Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.
=> Created 146_LRU_Cache.cpp

Solutions/1047. Remove All Adjacent Duplicates in String.cpp
Added two solutions using ::
- String Operations
- Stack Operations
Both solutions passed all the testcases successfully
=> Create 1047. Remove All Adjacent Duplicates in String.cpp

Important Questions., Solutions/1855. Maximum Distance Between a Pair of Values.cpp
Added three important questions with their links
1. Valid Anagram
2. Group Anagrams
3. Search in Rotated Sorted Array
=> Update Important Questions.
